### ISSUE TITLE
GitHub Authentication

### ISSUE THREAD

**Issue by MarchandMD** [dnvr-zero/dnvr-zero-fe#10]
- Determine which Oauth provider to use. 
- Github was super easy
- Google is more complicated than it needs to be
- this would need a link to allow a user to log into the site using their Github account
- this would also require a landing page for the person after they've successfully authenticated

**Comment by MarchandMD** [comment]
Does FE need anything from the BE for this? 

I was going to remove myself from this task if not.

**Comment by jfarelli** [comment]
Short Answer: 
Yes, you can take yourself off. 

Long Answer:
Ali found an article on how to do the Google OAuth, and I shared the article with her about the GitHub OAuth. 
We're going to read over them today/tomorrow. 
Think she's out until Tuesday, so I'm going to attempt the GitHub OAuth tomorrow/Sunday. 
We should probably incorporate both.

**Comment by MarchandMD** [comment]
cool. 

I've gone through the Google Cloud Platform a couple of times for Authentication, so I feel somewhat comfortable troubleshooting that. 

MVP included authentication, so Github, Google...the more the merrier. 

Beyond MVP though, allowing players to signup without authentication would be cool too. 

Also (beyond MVP) would be the idea of allowing a player to choose a name other than their Google/Github account. 

taken from the website about page: 

```Creating A New Character

What does it mean to create a new character in SFZero? Your character looks exactly the same as you. Your character will have all the same skills and attributes as you, and even the same memories and feelings. "Isn't my character, just, well, /me/?" Good question.

Your character has several important things that you do not have. First, your character has a Score. Its Score is a barometer of its progress.

You may find that your own willingness to interact with the city in new ways varies linearly with relation to your Score.

Second, your character will become affiliated with groups that you may or may not be affiliated with yourself. As you play SFZero, your decisions will determine which groups you are affiliated with.

Last, and most importantly, your character is able to do things that you may be unable or unwilling to do yourself. Your character doesn't recognize the artificial boundaries that prevent non-players from doing what they want to do. Things like fear, lethargy and the police don't deter your character from achieving his or her goals.

Your character never misses a connection - it will get you Score.

When you create a character please enter its full name, email address, the area in which it lives, and its username. You may also enter in the character's sex and physical home address. Although these are optional, they will enhance the game experience.

It will be helpful later on in the game if your character's address and geographic area are the same as yours. At this point you must also chose a group. For more information on group selection please see the "choosing a group" section of the manual.

Your character will receive its own personal web page. This page contains everything that your character has done in the game. 
```
